Feature/gallery
kadjialan/figma-page-react pull request #1
Opened 2023-01-16 15:44 UTC by kadjialan

Design of a Figma template  using reactjs

2023-01-17 09:58 UTC, gastonche requested changes
Take a look at these comments and handle them

2023-01-17 09:58 UTC, gastonche commented on src/App.jsx
> +        <Route path="*" element={<Blog />} />
The component here should not be blog. It should be a generic fallback component. So rename it to something more meaningful

2023-01-17 09:58 UTC, gastonche commented on src/Pages/About/Hero2/Hero2.jsx
> +export default function Hero2() {
Hero2 is not an appropriate name for a react component. Make the name more meaningful. Is it not AboutPageHeroSection?

2023-01-17 09:58 UTC, gastonche commented on src/Pages/About/Safarri/Safarri.css
> +.safarri__cards {
Nice going with the implementation of BEM here.

2023-01-17 09:58 UTC, gastonche commented on src/Pages/About/Safarri/Safarri.jsx
> +import Saf1 from '../../../asserts/images/saf1.png';
When importing files you want to give them the right names. Saf1, Saf2, Saf3 are all not valid here

2023-01-17 09:58 UTC, gastonche commented on src/Pages/About/Safarri/Safarri.jsx
> +        <div className="safarri__cards">
This section can be broken down into sub components. To make it more readable. but for now this is acceptable.

2023-01-17 09:58 UTC, gastonche commented on src/Pages/About/aaa.jsx
> +/* import React, { useEffect } from 'react'; */
This file seems useless. Please remove it.

2023-01-17 09:58 UTC, gastonche commented on src/Pages/Blog/Blog.jsx
> +export default function Blog() {
This component should probably be NotFound instead*

2023-01-17 09:58 UTC, gastonche commented on src/Pages/Contact/Contact.jsx
> +      <Hero3 data="Contact Us" text="Gallery" />
Should text here be Gallery?

2023-01-17 09:58 UTC, gastonche commented on src/Pages/Gallery/Pictures/Picture.jsx
> +import Pic1 from '../../../asserts/images/folder/pic1.png';
Again, we need meaningful names for file we import.

2023-01-17 09:58 UTC, gastonche commented on src/Pages/Gallery/Pictures/Picture.jsx
> +          <img src={Pic1} alt="afrique" className="pic" />
Is there a reason why you are not looping here?

2023-01-17 09:58 UTC, gastonche commented on src/components/Buttons/Buttons.jsx
> +export default function Buttons({ content }) {
This component should be called Button not Buttons. It displays one Button right?

2023-01-17 09:58 UTC, gastonche commented on src/components/Hero3/Hero3.jsx
> +export default function Hero3({ data, text }) {
This prop called data here, don't you think it should rather be called title?

2023-01-17 09:58 UTC, gastonche commented on src/components/Searchnav/Searchnav.jsx
>  export default function Searchnav() {
This component is call Searchnav. 

- Firstly it is not in camel case
- Also don't you think it should be named something else. Like is it really a "Search Nav bar"?

2023-06-19 09:58 UTC, okhot commented
Fix Linter errors

2023-06-19 11:25 UTC, closed without merging